### PR TITLE
sshpass replacement + Versioning + Bugfix in H80, H81 and binary creation

### PR DESCRIPTION
**Pull request by afsanac-nv**
**Major Changes**
- Fixes for missing import, dump path and binary location
- Added fix for common versioning and dynamic ssh ports
- sshpass replaced with sshtunnel library
- Fixed issue with SystemDetails argument
- Fixed testcases H80 and H81. The issue was - When the BasicHealthCheckTestGroup is run, H81 executes before H80. H81 deletes all subscriptions, so H80 finds an empty list of subscription. The solution is to create a sample event in case there is no events.

**Test Results**
- H80 and H81 run successfully both in group and independently.
- sshtunneling still works as expected with the change.
- CTAM binary creation works as expected. Tested by running the binary executable in different machines.
- Regression tests run with F0, F1 and BasicHealthCheckTestGroup.

### CODE REVIEW

**Comment by MeritedHobbit** [comment]
Looks like we are mandating **GetSystemDetails** with this change. We will need to avoid mandating this because the way to get details from BMC is not standardized yet. Once we have all move to OpenBMC, we can explore that. Can we revert this mandate?

**Comment by MeritedHobbit** [comment]
is_tunnel_established is unused...correct?

**Comment by MeritedHobbit** [comment]
Also, remote port needs to be flexible. Looks like the code forces remote redfish connection port as 80.

**Comment by MeritedHobbit** [comment]
Any reason why we need two ports for tunneling?

**Comment by MeritedHobbit** [comment]
Also I think we need to review the getes calls. Like this one under functional_ifc.py
                self.ctam_create_es(
                destination="https://172.17.0.202:8081/redfish/v1/RedfishEvents/EventReceiver/5",
                RegistryPrefixes="ResourceEvent", Context="rm_server_5", Protocol="Redfish")

**Comment by afsanac-nv** [comment]
After rebasing with developer branch, "-l" option broke. It is related some changes made in https://github.com/opencomputeproject/ocp-diag-ctam/pull/17/files#diff-6677de547a626a4f2188f90e2a36c7205685120fcd4cff6f0c49288fea9ca44fL64

**Pull request merged**
